services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes_from:
      - php

  php:
    image: php:8.0.12-fpm-alpine3.13
    container_name: php
    volumes:
      - type: bind
        source: ./source
        target: /app/
