services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./quicknotes:/app/
    links:
      - php

  php:
    image: php:7.4.3-fpm-alpine3.11
    container_name: php
    volumes:
      - ./quicknotes:/app/
