services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes_from:
      - php

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: php
    links:
      - postgres
    volumes:
      - type: bind
        source: ./source
        target: /app

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
